version: '3'

services:
    bgg:
        image: registry.gitlab.com/recommend.games/bgg-ranked-csv:0.0.2
        container_name: bgg-ranked-csv
        build: '.'
        env_file: .env
        volumes:
            - ../bgg-ranking-historicals:/bgg-ranking-historicals
